---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```

```{r, echo = TRUE, message = FALSE, warning = FALSE}
dat <- read_csv("Data/worldwidecases.csv")
```

\section*{Country Australia and China}


# The number of cases in each month of Australia
```{r}
# process the data to only contains information of Australia 
dat2 <- dat %>% dplyr::filter(countriesAndTerritories %in% c("Australia")
                                                          
)
```


```{r}
dat3 <- dat2 %>% dplyr::select(month,
                cases)

dat3 <- dat3 %>%
  group_by(month) %>%
  summarise_at(vars(cases),
               list(cases = sum))

kable(dat3, caption = "cases per month of Australia") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
p1 <- dat3 %>% ggplot(aes(x = month, y=cases)) +
  ggtitle("p1: cases in each month of Australia") +
  geom_point()
p1
``` 
# The number of cases in each month of China
```{r}
# process the data to only contains information of China 
dat4 <- dat %>% dplyr::filter(countriesAndTerritories %in% c("China")
                                                          
)
```


```{r}
dat5 <- dat4 %>% dplyr::select(month,
                cases)

dat5 <- dat5 %>%
  group_by(month) %>%
  summarise_at(vars(cases),
               list(cases = sum))

kable(dat5, caption = "cases per month of China") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
p2 <- dat5 %>% ggplot(aes(x = month, y=cases)) +
  ggtitle("p2: cases in each month of China") +
  geom_point()
p2
``` 